[package]
name = "light_novel_translator_iced"
version = "0.1.0"
edition = "2024"

[dependencies]
async-stream = "0.3.6"
base64 = "0.22.1"
epub = "2.1.5"
epub-builder = "0.8.2"
iced = { version = "0.14.0", features = ["advanced", "debug", "image", "lazy", "markdown", "svg", "tokio"] }
iced_aw = "0.13.0"
log = { version = "0.4.29" }
ollama-rs = { version = "0.3.4", features = ["stream", "tokio", "tokio-stream"] }
pulldown-cmark = "0.13.0"
quick-xml = { version = "0.39.1", features = ["tokio"] }
regex = "1.12.3"
rfd = { version = "0.17.2", features = ["xdg-portal"] }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["fs", "rt-multi-thread", "time", "tokio-macros"] }
tokio-stream = "0.1.18"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
